# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [32]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Name of the max valued product

In [33]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [34]:
chipo["item_price"] = chipo["item_price"].str.replace("$","")
chipo["item_price"]= chipo["item_price"].astype(float)

chipo["item_price"]

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [46]:
print("Artículo de mayor valor:", chipo["item_name"].loc[chipo["item_price"].idxmax()], chipo["item_price"].max(), "$")

Artículo de mayor valor: Chips and Fresh Tomato Salsa 44.25 $

In [53]:
chipo.loc[chipo["item_price"].idxmax()]

order_id                                      1443
quantity                                        15
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                   44.25
Name: 3598, dtype: object

### Step 4. How many products cost more than $10.00?

In [60]:
chipo[chipo["item_price"] > 10].shape[0]

1130

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [81]:
# No es lo mismo, porque en un mismo pedido se han comprado más productos y hay que mirar el order_id
chipo[chipo["item_price"] > 10]["order_id"].nunique()

863

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [ ]:
# No, hay que sumar todos los productos de un pedido y extraer aquellos que son > 10
pedidos_precio = chipo.groupby("order_id")["item_price"].sum()

print(pedidos_precio.min()) # todos son de más de 10

pedidos_precio[pedidos_precio > 10].size # da el número de pedidos de más de 10, que son todos

10.08

1834

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [180]:
# No, son productos de más de 10$ que se haya comprado más de 2 veces en un mismo order_id
productos_mas_de_10 = chipo[chipo["quantity"] >= 2]
productos_mas_de_10 = productos_mas_de_10[productos_mas_de_10["item_price"] > 10]
productos_mas_de_10

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
135,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",22.50
148,67,2,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Chees...",17.98
150,68,2,Chicken Burrito,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",17.50
154,70,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50
...,...,...,...,...,...
4423,1764,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",22.50
4427,1764,2,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Sour ...",23.50
4435,1767,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",17.50
4489,1786,4,Chips and Guacamole,NaN,17.80
4561,1813,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",17.50

In [181]:
num_pedidos = productos_mas_de_10["order_id"].nunique()

print("El número de pedidos donde se ha comprado un mismo producto de más de 10$ es de", 
      num_pedidos)

El número de pedidos donde se ha comprado un mismo producto de más de 10$ es de 117

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [182]:
productos_mas_de_10["unit_price"] = productos_mas_de_10["item_price"]/productos_mas_de_10["quantity"]
extraccion= productos_mas_de_10[["item_name", "unit_price"]]
extraccion

                item_name  unit_price
4            Chicken Bowl        8.49
135    Chicken Salad Bowl       11.25
148         Steak Burrito        8.99
150       Chicken Burrito        8.75
154          Chicken Bowl        8.75
...                   ...         ...
4423         Chicken Bowl       11.25
4427           Steak Bowl       11.75
4435         Chicken Bowl        8.75
4489  Chips and Guacamole        4.45
4561   Chicken Salad Bowl        8.75

[133 rows x 2 columns]

### Step 6. Sort by the name of the item

In [183]:
extraccion.sort_values(by="item_name")

                  item_name  unit_price
3389      6 Pack Soft Drink        6.49
1903  Barbacoa Crispy Tacos        9.25
3599          Bottled Water        1.50
4152          Bottled Water        1.50
445                    Bowl        7.40
...                     ...         ...
4354       Steak Soft Tacos        9.25
3617            Veggie Bowl        8.49
846             Veggie Bowl        8.49
3601         Veggie Burrito       11.25
3889      Veggie Soft Tacos        8.49

[133 rows x 2 columns]

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [ ]:
# VERSION 1
productos_mas_de_10_sorted = productos_mas_de_10.sort_values(by="unit_price", ascending= False).reset_index()
print(f"La candidad del producto más caro ({productos_mas_de_10_sorted["item_name"].loc[0]}: {productos_mas_de_10_sorted["unit_price"].loc[0]}$) ha sido de {productos_mas_de_10_sorted["quantity"].loc[0]}.")

La candidad del producto más caro (Steak Salad Bowl: 11.89$) ha sido de 2.

In [ ]:
# VERSION 2
productos_mas_de_10 = productos_mas_de_10.reset_index()
productos_mas_de_10

,index,order_id,quantity,item_name,choice_description,item_price,unit_price
0,4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
1,135,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",22.50,11.25
2,148,67,2,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Chees...",17.98,8.99
3,150,68,2,Chicken Burrito,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",17.50,8.75
4,154,70,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50,8.75
...,...,...,...,...,...,...,...
128,4423,1764,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",22.50,11.25
129,4427,1764,2,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Sour ...",23.50,11.75
130,4435,1767,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",17.50,8.75
131,4489,1786,4,Chips and Guacamole,NaN,17.80,4.45
132,4561,1813,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",17.50,8.75

In [191]:
maximo = productos_mas_de_10["unit_price"].max()
maximo_idx = productos_mas_de_10["unit_price"].idxmax()
# print(maximo)
# print(maximo_idx)

print(f"La candidad del producto más caro ({productos_mas_de_10["item_name"][maximo_idx]}: {maximo}$) ha sido de {productos_mas_de_10["quantity"][maximo_idx]}.")

La candidad del producto más caro (Steak Salad Bowl: 11.89$) ha sido de 2.

In [138]:
extraccion.max()

item_name     Veggie Soft Tacos
unit_price                11.89
dtype: object

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [ ]:
# OPCION 1
veggie_salad_bowl = chipo[chipo["item_name"] == "Veggie Salad Bowl"]
veggie_salad_bowl.shape[0]

18

In [219]:
# OPCIÓN 2
frecuencias = chipo.value_counts("item_name") 
frecuencias["Veggie Salad Bowl"]

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [225]:
chipo[(chipo["quantity"] >= 2) & (chipo["item_name"] == "Canned Soda")].shape[0]

20