# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [244]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [245]:
chipo["item_price"].max()

'$9.39 '

### Step 3. Name of the max valued product

In [246]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [247]:
chipo["item_price"] = chipo["item_price"].str.replace("$","")
chipo["item_price"]= chipo["item_price"].astype(float)

chipo["unit_price"] = chipo["item_price"] / chipo["quantity"]

In [248]:
prod_caros = chipo[chipo["unit_price"] == chipo["unit_price"].max()]
print(prod_caros["item_name"].unique(), prod_caros["unit_price"].unique())

<StringArray>
['Steak Salad Bowl', 'Carnitas Salad Bowl', 'Barbacoa Salad Bowl']
Length: 3, dtype: str [11.89]

In [249]:
# De esta otra forma, perdemos la info de que os otros dos productos tienen también el mismo precio
print("Artículo de mayor valor:", chipo["item_name"].loc[chipo["unit_price"].idxmax()], chipo["unit_price"].max(), "$")

Artículo de mayor valor: Steak Salad Bowl 11.89 $

In [254]:
chipo.loc[chipo["unit_price"].idxmax(), ["item_name", "item_price", "quantity"]]

item_name     Steak Salad Bowl
item_price               23.78
quantity                     2
Name: 281, dtype: object

### Step 4. How many products cost more than $10.00?

In [258]:
productos_caros = chipo[chipo["unit_price"] > 10]
productos_caros["item_name"].nunique()

25

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [259]:
# No es lo mismo, porque en un mismo pedido se han comprado más productos y hay que mirar el order_id
productos_caros["order_id"].nunique()

787

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [279]:
# No, hay que sumar todos los productos de un pedido y extraer aquellos que son > 10
pedidos_precio = chipo.groupby("order_id")["item_price"].sum()

print(pedidos_precio.min()) # todos son de más de 10

pedidos_precio[pedidos_precio > 10].size # da el número de pedidos de más de 10, que son todos

10.08

1834

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [277]:
# No, son productos de más de 10$ que se haya comprado más de 2 veces en un mismo order_id
productos_mas_de_10 = chipo[chipo["quantity"] >= 2]
productos_mas_de_10 = productos_mas_de_10[productos_mas_de_10["unit_price"] > 10]
productos_mas_de_10.head()

,order_id,quantity,item_name,choice_description,item_price,unit_price
135,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",22.50,11.25
213,94,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",22.50,11.25
281,123,2,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",23.78,11.89
353,152,2,Steak Burrito,"[Fresh Tomato (Mild), [Lettuce, Guacamole, Ric...",22.16,11.08
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",32.94,10.98

In [276]:
num_pedidos = productos_mas_de_10["order_id"].nunique()

print("El número de pedidos donde se ha comprado un mismo producto de más de 10$ es de", 
      num_pedidos)

El número de pedidos donde se ha comprado un mismo producto de más de 10$ es de 36

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [285]:
chipo[["item_name", "unit_price"]].head()

                               item_name  unit_price
0           Chips and Fresh Tomato Salsa        2.39
1                                   Izze        3.39
2                       Nantucket Nectar        3.39
3  Chips and Tomatillo-Green Chili Salsa        2.39
4                           Chicken Bowl        8.49

### Step 6. Sort by the name of the item

In [286]:
chipo.sort_values(by="item_name")

,order_id,quantity,item_name,choice_description,item_price,unit_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49,6.49
...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [295]:
# VERSION 1 (con todo el dataset)
chipo_sorted = chipo.sort_values(by="item_price", ascending= False).reset_index()

print(f"La candidad del producto más caro ({chipo_sorted["item_name"].loc[0]}: {chipo_sorted["item_price"].loc[0]}$) ha sido de {chipo_sorted["quantity"].loc[0]}.")

La candidad del producto más caro (Chips and Fresh Tomato Salsa: 44.25$) ha sido de 15.

In [300]:
# VERSION 2 (con todo el dataset)
maximo = chipo["item_price"].max()
maximo_idx = chipo["item_price"].idxmax()
# print(maximo)
# print(maximo_idx)

print(f"La candidad del producto más caro ({chipo["item_name"].iloc[maximo_idx]}: {maximo}$) ha sido de {chipo["quantity"].iloc[maximo_idx]}.")

La candidad del producto más caro (Chips and Fresh Tomato Salsa: 44.25$) ha sido de 15.

In [298]:
# VERSION 3 (con todo el dataset)
chipo[["item_name", "item_price"]].max()

item_name     Veggie Soft Tacos
item_price                44.25
dtype: object

In [289]:
# VERSION 1 (con el df precios > 10)
productos_mas_de_10_sorted = productos_mas_de_10.sort_values(by="unit_price", ascending= False).reset_index()

print(f"La candidad del producto más caro ({productos_mas_de_10_sorted["item_name"].loc[0]}: {productos_mas_de_10_sorted["unit_price"].loc[0]}$) ha sido de {productos_mas_de_10_sorted["quantity"].loc[0]}.")

La candidad del producto más caro (Steak Salad Bowl: 11.89$) ha sido de 2.

In [283]:
productos_mas_de_10_sorted.head()

,index,order_id,quantity,item_name,choice_description,item_price,unit_price
0,281,123,2,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",23.78,11.89
1,613,253,2,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",23.78,11.89
2,1566,635,2,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",23.50,11.75
3,506,212,2,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",23.50,11.75
4,1753,708,2,Steak Burrito,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",23.50,11.75

In [185]:
# VERSION 2 (con el df precios > 10)
productos_mas_de_10 = productos_mas_de_10.reset_index()
productos_mas_de_10

,index,order_id,quantity,item_name,choice_description,item_price,unit_price
0,4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
1,135,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",22.50,11.25
2,148,67,2,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Chees...",17.98,8.99
3,150,68,2,Chicken Burrito,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",17.50,8.75
4,154,70,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50,8.75
...,...,...,...,...,...,...,...
128,4423,1764,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",22.50,11.25
129,4427,1764,2,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Sour ...",23.50,11.75
130,4435,1767,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",17.50,8.75
131,4489,1786,4,Chips and Guacamole,NaN,17.80,4.45
132,4561,1813,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",17.50,8.75

In [191]:
maximo = productos_mas_de_10["unit_price"].max()
maximo_idx = productos_mas_de_10["unit_price"].idxmax()
# print(maximo)
# print(maximo_idx)

print(f"La candidad del producto más caro ({productos_mas_de_10["item_name"][maximo_idx]}: {maximo}$) ha sido de {productos_mas_de_10["quantity"][maximo_idx]}.")

La candidad del producto más caro (Steak Salad Bowl: 11.89$) ha sido de 2.

In [138]:
extraccion.max()

item_name     Veggie Soft Tacos
unit_price                11.89
dtype: object

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [306]:
# OPCION 1
veggie_salad_bowl = chipo[chipo["item_name"] == "Veggie Salad Bowl"]["quantity"].sum()
veggie_salad_bowl

np.int64(18)

In [219]:
# OPCIÓN 2
frecuencias = chipo.value_counts("item_name") 
frecuencias["Veggie Salad Bowl"]

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [313]:
chipo.loc[(chipo["quantity"] >= 2) & (chipo["item_name"] == "Canned Soda"), "order_id"].nunique()

18

In [314]:
chipo.loc[chipo["order_id"] == 450] # en el mismo pedido, han pedido dos veces Canned Soda

,order_id,quantity,item_name,choice_description,item_price,unit_price
1091,450,2,Canned Soda,[Dr. Pepper],2.18,1.09
1092,450,2,Canned Soda,[Coca Cola],2.18,1.09
1093,450,1,Steak Burrito,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",11.48,11.48